### ISSUE TITLE
matplotlib 3.1.1 cairo backend error

### ISSUE THREAD

**Issue by bwmeyers** [bwmeyers/tauclean#4]
Matplotlib 3.1.1 doesn't seem to play well with this at the moment, specifically complaining with

`AttributeError: module 'cairo' has no attribute 'version_info'`

**Comment by bwmeyers** [comment]
Seems to have been resolved. I can't reproduce the error.

**Comment by QingyueMeng** [comment]
I have trouble in this error, too. Could you tell me how to solve it?

**Comment by bwmeyers** [comment]
I can't reproduce it, so I don't know how to fix it. Can you tell me what version of `matplotlib` you're using?

**Comment by bwmeyers** [comment]
@QingyueMeng Did you manage to solve the problem, or is it still causing you problems. I think that the initial problem ended up being due to a different PNG library used by CentOS, but perhaps an updated version of that library or `matplotlib` will help?
